const moradores = [
    {
        nome: "Biel",
        curso: "Engenharia Física, UFSCar",
        ano: "2019",
        foto: "6",
        insta: "insta_biel",
    },
    {
        nome: "Dog",
        curso: "Engenharia Elétrica, CAASO",
        ano: "2019",
        foto: "18",
        insta: "insta_dog",
    },
    {
        nome: "Xupeta",
        curso: "Processos Gerenciais, IFSP",
        ano: "2019",
        foto: "8",
        insta: "insta_xupeta",
    },
    {
        nome: "Igart",
        curso: "Química, UFSCar",
        ano: "2019",
        foto: "1",
        insta: "insta_igart",
    },
    {
        nome: "Gico",
        curso: "Química, UFSCar",
        ano: "2019",
        foto: "16",
        insta: "insta_gico",
    },
    {
        nome: "Hill",
        curso: "Engenharia de Produção, UFSCar",
        ano: "2019",
        foto: "1",
        insta: "insta_hill",
    },
    {
        nome: "Jin",
        curso: "Engenharia de Produção, UFSCar",
        ano: "2020",
        foto: "7",
        insta: "insta_jin",
    },
    {
        nome: "Gito",
        curso: "Engenharia Mecânica, UFSCar",
        ano: "2020",
        foto: "5",
        insta: "insta_gito",
    },
    {
        nome: "Math",
        curso: "Engenharia de Produção, CAASO",
        ano: "2020",
        foto: "4",
        insta: "vinivrd",
    },
    {
        nome: "Pagode",
        curso: "Engenharia Civil, UFSCar",
        ano: "2020",
        foto: "3",
        insta: "insta_pagode",
    },
    {
        nome: "Bruxo",
        curso: "Engenharia Civil, CAASO",
        ano: "2020",
        foto: "14",
        insta: "insta_bruxo",
    },
    {
        nome: "Sampa",
        curso: "Engenharia Civil, UFSCar",
        ano: "2021",
        foto: "1",
        insta: "insta_sampa",
    },
    {
        nome: "Dona Lu",
        curso: "Cuidar da Casa",
        ano: "2021",
        foto: "1",
        insta: "insta_donalu",
    },
    {
        nome: "Bola",
        curso: "Engenharia de Materiais, UFSCar",
        ano: "2022",
        foto: "17",
        insta: "insta_bola",
    },
    {
        nome: "Soca",
        curso: "Estatística e Ciências de Dados, CAASO",
        ano: "2022",
        foto: "9",
        insta: "insta_soca",
    },
    {
        nome: "Mister",
        curso: "Engenharia Civil, UFSCar",
        ano: "2022",
        foto: "15",
        insta: "insta_mister",
    },
    {
        nome: "Dudu",
        curso: "Engenharia Civil, UFSCar",
        ano: "2023",
        foto: "10",
        insta: "insta_dudu",
    },
    {
        nome: "Kenner",
        curso: "Estatística e Ciências de Dados, CAASO",
        ano: "2023",
        foto: "13",
        insta: "insta_kenner",
    },
    {
        nome: "Menex",
        curso: "Engenharia Mecânica, UFSCar",
        ano: "2023",
        foto: "11",
        insta: "insta_menex",
    },
    {
        nome: "Pinguim",
        curso: "Física Licenciatura, UFSCar",
        ano: "2023",
        foto: "12",
        insta: "insta_pinguim",
    },
    {
        nome: "Canastra",
        curso: "Engenharia Elétrica, CAASO",
        ano: "2023",
        foto: "1",
        insta: "insta_canastra",
    },
    {
        nome: "Vini",
        curso: "Bacharelado em Sistemas de Informação, CAASO",
        ano: "2023",
        foto: "2",
        insta: "insta_vini",
    },
    {
        nome: "Deco",
        curso: "Bagunçar a Casa",
        ano: "2023",
        foto: "1",
        insta: "insta_deco",
    },
];

export default moradores;
